UPDATE restaurants SET name_zh='MO-MO-PARADISE 新宿东口店' WHERE id='ChIJvUEnaNqMGGAR46u74Waa6FM';
UPDATE restaurants SET name_zh='山城辣妹子 重庆火锅 上野店' WHERE id='ChIJKa3nPwCPGGARq8If2YH0xQo';
UPDATE restaurants SET name_zh='陕西面馆' WHERE id='ChIJ174E2_eNGGARy7RsE-BIpxo';
UPDATE restaurants SET name_zh='海底捞火锅 上野店' WHERE id='ChIJ_Ubi3cONGGARMBSwSl4PTDY';
UPDATE restaurants SET name_zh='百味面馆' WHERE id='ChIJ07e1X22NGGAR9MR2UA15JIk';
UPDATE restaurants SET name_zh='肉汁水饺子 饺包 新宿店' WHERE id='ChIJH3x3gCONGGARd8ZXaVNQmcI';
UPDATE restaurants SET name_zh='炭火羊肉串 阿里香 新宿店' WHERE id='ChIJ2WSPpjSNGGAREwYnf7p_FDk';
UPDATE restaurants SET name_zh='2100K冒鸭烫肚高田马场店' WHERE id='ChIJgQz3YQCNGGARmwC1a5eFP-0';
UPDATE restaurants SET name_zh='MO-MO-PARADISE 新宿三丁目店' WHERE id='ChIJX63OU9qMGGAReYZ5uABXAro';
UPDATE restaurants SET name_zh='琉球チャイニーズ シシシ 新宿本店' WHERE id='ChIJO7VizduNGGAR2buzH5fA-h8';
UPDATE restaurants SET name_zh='海底捞火锅 新宿店' WHERE id='ChIJL8BoBzWNGGARNo99re1UTOc';
UPDATE restaurants SET name_zh='李暁七マーラータン新大久保店' WHERE id='ChIJP0qMjWyNGGAR9sJAlUvf71w';
UPDATE restaurants SET name_zh='杨国福 麻辣汤 高田马场店' WHERE id='ChIJve6_Pf-NGGARkMdRqV85yW4';
UPDATE restaurants SET name_zh='天府火锅巷子（池袋店）TIANFU HOTPOT IKEBUKURO' WHERE id='ChIJ3zD3xqiNGGAR6oUP9lCuTxo';
UPDATE restaurants SET name_zh='2100K冒鸭烫肚 池袋店' WHERE id='ChIJL4oGqJ2NGGARk2W8tO5HoOg';
UPDATE restaurants SET name_zh='天府李米线 高田马场店' WHERE id='ChIJMcwARtmNGGARMWJ26mePRYQ';
UPDATE restaurants SET name_zh='岁岁红 上野店' WHERE id='ChIJ4eDTcIePGGARonkuA3iNoHk';
UPDATE restaurants SET name_zh='马子禄牛肉面 新宿店' WHERE id='ChIJrQqrVryNGGARpkBvJrMeXnQ';
UPDATE restaurants SET name_zh='渝小渝鲜汤爆炒' WHERE id='ChIJxY2oIJqPGGARCoH1TV1UpMA';
UPDATE restaurants SET name_zh='汤火功夫 高田马场店' WHERE id='ChIJOfqSSwCNGGARBjA6NUM5cAE';
UPDATE restaurants SET name_zh='成都娘酸菜鱼 成都姑娘' WHERE id='ChIJgQMKHouNGGARb9dkcb0Hv30';
UPDATE restaurants SET name_zh='三顾冒菜' WHERE id='ChIJ_-VBawCNGGARn52xGtJRE_4';
UPDATE restaurants SET name_zh='ヤミーマーラータン 야미마라탕' WHERE id='ChIJjRiVbwCNGGARRUvXxnvsVFU';
UPDATE restaurants SET name_zh='川香苑' WHERE id='ChIJg_xskXWNGGAR1dBo0-Zg26s';
UPDATE restaurants SET name_zh='望滇山 酸汤养生火锅 上野店' WHERE id='ChIJL6pUvVGPGGARPtZQ9xT_Kqo';
UPDATE restaurants SET name_zh='蜀签（ショクセン)' WHERE id='ChIJU3DhAgCNGGARU-p9gTuBvwM';
UPDATE restaurants SET name_zh='牛家兄弟兰州牛肉面 高田马场店(halal)' WHERE id='ChIJPcqd3ZGNGGARPHii3VfiZCk';
UPDATE restaurants SET name_zh='广东料理 海港美食' WHERE id='ChIJI85ezAWPGGARhCJYtLh8zsA';
UPDATE restaurants SET name_zh='西安𰻞𰻞面（ビャンビャン面） 西北高家 龟户店' WHERE id='ChIJo5BNXwCJGGARG-xaQYsZDkY';
UPDATE restaurants SET name_zh='順順マーラータン' WHERE id='ChIJu0pYCACJGGARxfJayTv0Xvc';
UPDATE restaurants SET name_zh='丝绸之路维吾尔料理 ALIBABA HALAL 上野' WHERE id='ChIJV3d9cgCPGGARvLdUCbW-I_o';
UPDATE restaurants SET name_zh='海底捞火锅 池袋店' WHERE id='ChIJeaoKD2iNGGARbBkqYsU-Sgs';
UPDATE restaurants SET name_zh='酥肉坊' WHERE id='ChIJKTs4XzqNGGAR6YNgG2kJ41s';
UPDATE restaurants SET name_zh='亲爱的麻辣汤' WHERE id='ChIJQTi85yGNGGARhbgsNMlPhdc';
UPDATE restaurants SET name_zh='羊贵族 池袋北口店' WHERE id='ChIJi4evBl6NGGARvYlWVq4yOic';
UPDATE restaurants SET name_zh='四川火锅涮涮锅专卖店 贤合庄' WHERE id='ChIJT233-pKNGGAReD7zrE0rJA0';
UPDATE restaurants SET name_zh='杨国福麻辣烫大久保店' WHERE id='ChIJs_EN_CmNGGARX2Vt3V7Y-ho';
UPDATE restaurants SET name_zh='大丰收铁锅炖 池袋西口店' WHERE id='ChIJj6AxbTeNGGAR9HwPBKYrQTM';
UPDATE restaurants SET name_zh='牛腩面馆 新仙' WHERE id='ChIJ_US6NQCNGGAR_RNYx4YqR_8';
UPDATE restaurants SET name_zh='威皇花雕醉鸡锅&广东料理 六本木店' WHERE id='ChIJrXSOSvWLGGARCYkdscforLU';
UPDATE restaurants SET name_zh='麻香源麻辣烫' WHERE id='ChIJ_2-tY-zzGGAR0SVUTYpkXKM';
UPDATE restaurants SET name_zh='桦南大碗麻辣烫大久保店' WHERE id='ChIJz1Qz-YqNGGARqPQeSCf9vAM';
UPDATE restaurants SET name_zh='三顾冒菜' WHERE id='ChIJQ0_kIACJGGARxyPlVoElwpw';
UPDATE restaurants SET name_zh='麻辣火锅专卖店 越智' WHERE id='ChIJh_dkTB6NGGARt8JMdutQmG8';
UPDATE restaurants SET name_zh='ポポホー' WHERE id='ChIJ89lVn_KLGGAR4b13rKk0ktE';
UPDATE restaurants SET name_zh='湘泉・湖南菜' WHERE id='ChIJHzChIwCNGGARIL_yIJ0t9jk';
UPDATE restaurants SET name_zh='灶财进宝 小锅呼饼铁锅炖' WHERE id='ChIJD15k2puPGGARxQKTDS-ckhs';
UPDATE restaurants SET name_zh='杨国福麻辣汤 东京银座店' WHERE id='ChIJH9ZWegCLGGARb2iSBh4bITo';
UPDATE restaurants SET name_zh='Caravan キャラバン 喀尔湾' WHERE id='ChIJ0abs1OeNGGARyJCGwJ7pJWQ';
UPDATE restaurants SET name_zh='2100K冒鸭烫肚 上野店' WHERE id='ChIJm7lgYgCPGGARhUl0cnWWt5Q';
UPDATE restaurants SET name_zh='湘南饭店 浅草本店' WHERE id='ChIJDQ6GcQCPGGARFGDaH9yZG2Y';
UPDATE restaurants SET name_zh='楼上重庆火锅 池袋店' WHERE id='ChIJ7Z-ywmaNGGAR11I6NndgGOk';
UPDATE restaurants SET name_zh='666麻辣汤 上野' WHERE id='ChIJ78bvIE-PGGARtniUKB9y3YU';
UPDATE restaurants SET name_zh='楼上重庆火锅 上野店' WHERE id='ChIJa6swQgCPGGARq3N1Gyem1KY';
UPDATE restaurants SET name_zh='天府李米线 TINA''S NOODLE KITCHEN' WHERE id='ChIJW4ZrT36PGGARWhiG0nFXGTk';
UPDATE restaurants SET name_zh='亲爱的麻辣汤 上野店' WHERE id='ChIJQeLgRwCPGGARfsl8Vffc2qM';
UPDATE restaurants SET name_zh='凡姐老火锅 池袋店' WHERE id='ChIJDyjcMTeNGGARc2E7RCeRx5k';
UPDATE restaurants SET name_zh='HALAL中华 阿丽娅アリヤ 清真美食 上野店' WHERE id='ChIJHWL7fCSPGGARzsrKJdTQEoI';
UPDATE restaurants SET name_zh='蓉城饭局' WHERE id='ChIJ-wfOKM2PGGARRNtf23Q6_dc';
UPDATE restaurants SET name_zh='Doppam' WHERE id='ChIJ67zrHgDtGGARDVz5zqrRPgg';
UPDATE restaurants SET name_zh='张大大金汤麻辣汤' WHERE id='ChIJ75ALevqJGGARALk2dBwaKXQ';
UPDATE restaurants SET name_zh='マーラータン 転転麻辣湯 代官山本店' WHERE id='ChIJMXilXjCLGGARGAi2PBFNHaY';
UPDATE restaurants SET name_zh='江西饭店(原「金喜悦」)' WHERE id='ChIJOSlcQr6NGGARovFNCQUGBQI';
UPDATE restaurants SET name_zh='赤坂マーラータン 新中野店' WHERE id='ChIJ1_3EDQDzGGAR3seZ09_wFWE';
UPDATE restaurants SET name_zh='卓尚记 九五龙虾' WHERE id='ChIJLS4hP2SNGGARJX3c2ZfPTio';
UPDATE restaurants SET name_zh='四川料理 巴蜀' WHERE id='ChIJ2x2zqJKPGGARm8MFQ0gBMRc';
UPDATE restaurants SET name_zh='渝火火・ユホホ・重慶老火鍋' WHERE id='ChIJo2QjcQCNGGAR-7G4nWkt07g';
UPDATE restaurants SET name_zh='熊猫火锅 上野店' WHERE id='ChIJVa6rjPqPGGARZUTR5wgKKXs';
UPDATE restaurants SET name_zh='四川麻辣汤 下北泽星星俱乐部' WHERE id='ChIJmUWZBALzGGARSTK5fwGMpsU';
UPDATE restaurants SET name_zh='金太饭店' WHERE id='ChIJBXKXje2NGGARd_ZfN8bF7_o';
UPDATE restaurants SET name_zh='麻辣汤 PANDA ZHU (パンダチュウ)' WHERE id='ChIJRSluPgCNGGARw-aqIOu3KTY';
UPDATE restaurants SET name_zh='味上湖南菜馆 新宿店' WHERE id='ChIJLaU6YQCNGGAR7vG7Mq9aMkE';
UPDATE restaurants SET name_zh='中华料理 延雅村（ヨナマウル）上野駅前店' WHERE id='ChIJ660NQKSPGGARCy3CWManlNE';
UPDATE restaurants SET name_zh='秋雨麻辣汤（药膳スープ・マーラータン）' WHERE id='ChIJg7ffdiGJGGARvJQlrts_9rM';
UPDATE restaurants SET name_zh='ウイグル料理 刀郎(DOLAN) 2号店' WHERE id='ChIJmUq9bQCNGGARRrT_mgzXyc8';
UPDATE restaurants SET name_zh='赤丸' WHERE id='ChIJv0KwGhuGGGAR7ORZTEJzI00';
UPDATE restaurants SET name_zh='七福 麻辣汤' WHERE id='ChIJhQGKtRSNGGARVhsGtw5HqPQ';
UPDATE restaurants SET name_zh='熊猫火锅 池袋店' WHERE id='ChIJnw0JmReNGGARHQh5UsC7e4I';
UPDATE restaurants SET name_zh='兰州陈记牛肉面＆无名缘米粉 池袋本店' WHERE id='ChIJiyF7_gWNGGAR_3gMHFgEKLM';
UPDATE restaurants SET name_zh='匠雕风情(ショウチョウフゼイ)' WHERE id='ChIJW85UJUGLGGAR2a9_fXbynh4';
UPDATE restaurants SET name_zh='药膳麻辣汤锅 羊美人（ヤンメイレン）' WHERE id='ChIJXZg6CGyNGGARRPij_qFe8B0';
UPDATE restaurants SET name_zh='杨国福 东京上野店' WHERE id='ChIJHd6C09ePGGARX7gcmKqMtf8';
UPDATE restaurants SET name_zh='ヤンチャン麻辣汤' WHERE id='ChIJWeQHBgbzGGARc2alDwoBkWg';
UPDATE restaurants SET name_zh='中国菜 仁' WHERE id='ChIJ_wC5xrSPGGARqBmAjSelBts';
UPDATE restaurants SET name_zh='（汤）重庆火锅' WHERE id='ChIJn0Z61tmHGGARVcaJ4QrbPtM';
UPDATE restaurants SET name_zh='小东北 味妳而来' WHERE id='ChIJnfeYsxeNGGARo2YMcXMv0uY';
UPDATE restaurants SET name_zh='连湘阁 湖南菜' WHERE id='ChIJv27FWACNGGARUu8MQPweti0';
UPDATE restaurants SET name_zh='久久老火锅' WHERE id='ChIJfQIStMmNGGARkjfPqYbgYIo';
UPDATE restaurants SET name_zh='ウイグル料理 DOLAN＆牛家兄弟 兰州牛肉面 池袋本店（Halalハラール）' WHERE id='ChIJQQk-TTuNGGARcdf9Xg8NnWQ';
UPDATE restaurants SET name_zh='回转火锅 转多多 中华料理' WHERE id='ChIJ4ft_BQCNGGARGuH-8BERfoI';
UPDATE restaurants SET name_zh='吉聚阁' WHERE id='ChIJsYooJN-JGGAReNjWrq3vPWg';
UPDATE restaurants SET name_zh='金陵赤坂店' WHERE id='ChIJURjYQtCNGGARCbz-uLmJVy4';
UPDATE restaurants SET name_zh='旬华なか村' WHERE id='ChIJxWXHuVmJGGAReZRYkwm3siY';
UPDATE restaurants SET name_zh='李晓七マーラータン 新小岩店' WHERE id='ChIJ2URgeQCHGGARj9FrQntgdQk';
UPDATE restaurants SET name_zh='SHEEPMAN シープマン 池袋店' WHERE id='ChIJO4m9Bq-NGGAR2rhTLs8-UtU';
UPDATE restaurants SET name_zh='翠云' WHERE id='ChIJ453-faKNGGARzl8XPBKDCEY';
UPDATE restaurants SET name_zh='王记 兰州拉面' WHERE id='ChIJAx9cVQBhGGARBa4zIVr0W68';
UPDATE restaurants SET name_zh='小河帮川菜 上野店' WHERE id='ChIJhYoxYQCPGGARHowpR_Xde3I';
UPDATE restaurants SET name_zh='香港饭店0410 赤坂店' WHERE id='ChIJxQAImJqLGGARmr6a_Gy6YJ0';
UPDATE restaurants SET name_zh='东京黔大叔烙锅酒场（チェンダスウ）' WHERE id='ChIJBzgCROyNGGARKW3uQPYT0PQ';
UPDATE restaurants SET name_zh='唇辣道(チュンラードゥ)·中国菜 池袋店' WHERE id='ChIJ95c3qbqNGGARHpURLUnqAdo';
UPDATE restaurants SET name_zh='ラホンバンマーラータン 高田馬場店' WHERE id='ChIJ9YGBN8iNGGARE05jy178ml8';
UPDATE restaurants SET name_zh='香港饭店0410 上野店' WHERE id='ChIJNX4fSeSPGGARBlmjyMY1e5Y';
UPDATE restaurants SET name_zh='食彩 清真小厨 ハラールキッチン' WHERE id='ChIJm3HYBZ-NGGARefUsZwlw-nI';
UPDATE restaurants SET name_zh='四川史菜彩芳' WHERE id='ChIJL6OapKCOGGARlTN8GtGmxqg';
UPDATE restaurants SET name_zh='中国饭店 富丽华' WHERE id='ChIJreMNLr2LGGARdYxzqsotyOo';
UPDATE restaurants SET name_zh='Karghay - Halal 町工場' WHERE id='ChIJPed9IgCNGGARifRQqiyw3cw';
UPDATE restaurants SET name_zh='どんきい' WHERE id='ChIJ2wN5UASGGGART-CJjboeUaI';
UPDATE restaurants SET name_zh='楼上重庆火锅店 小岩店' WHERE id='ChIJW9Z21umFGGARkMb_Hi7ZpzI';
UPDATE restaurants SET name_zh='行辺' WHERE id='ChIJa68Y08PzGGARmkSdTHKqjU0';
UPDATE restaurants SET name_zh='兰州清汤牛肉面 陇垣金城' WHERE id='ChIJp-exgKiNGGAR10GMB9b0j_0';
UPDATE restaurants SET name_zh='福建' WHERE id='ChIJ1ca36vOSGGARhS4yGRnkoIk';
UPDATE restaurants SET name_zh='中华料理 大上海麻辣汤 新小岩' WHERE id='ChIJ5Z1dRxuGGGARSCcwoTbD3zI';
UPDATE restaurants SET name_zh='中国西北料理 大新疆' WHERE id='ChIJITxb--2NGGARqmN4xBCKjmc';
UPDATE restaurants SET name_zh='杨国福麻辣烫 上野駅前店' WHERE id='ChIJa_RDwLOPGGARW2bQyKVQDok';
UPDATE restaurants SET name_zh='中国南部家庭料理の旅～南方急行' WHERE id='ChIJyS_SfACNGGAR7t1kxtIzTtQ';
UPDATE restaurants SET name_zh='唐家' WHERE id='ChIJ53kwOe-HGGARItrMH61ER6s';
UPDATE restaurants SET name_zh='王府饺子酒场 新小岩店' WHERE id='ChIJve6ausuHGGARjFgAZMAVhog';
UPDATE restaurants SET name_zh='盛兴顺铁锅炖 池袋店' WHERE id='ChIJSZ1mkAiNGGARBiFMMN10j78';
UPDATE restaurants SET name_zh='中国菜 汉' WHERE id='ChIJjaGsyLiLGGARqhB_pSgosxI';
UPDATE restaurants SET name_zh='二刀流麻辣汤金町店' WHERE id='ChIJR5MNLwCFGGAR-Ysc5DxEKAw';
UPDATE restaurants SET name_zh='中国料理 カントニーズ 燕 丸の内' WHERE id='ChIJ-yVLzvuLGGARQXkX-eEKoBg';
UPDATE restaurants SET name_zh='四川家庭料理 珍珍（ゼンゼン）' WHERE id='ChIJB37seNyFGGAREKaWzMU3Csk';
UPDATE restaurants SET name_zh='南方中华料理 南三' WHERE id='ChIJR6Z4k9qNGGARo4cCrx3woJY';
UPDATE restaurants SET name_zh='银座 飞雁阁' WHERE id='ChIJbZmZZOiLGGAR8IftZZhdNec';
UPDATE restaurants SET name_zh='中国菜ARATA' WHERE id='ChIJafsdD46JGGARbIk9f8wR384';
UPDATE restaurants SET name_zh='私房菜吉田' WHERE id='ChIJ21ZWRc2LGGARLj3q0l-v-gs';
UPDATE restaurants SET name_zh='成都馆' WHERE id='ChIJHfgQlA2PGGAR1Pum5kPd_Ac';
UPDATE restaurants SET name_zh='中华料理 新仙 新宿东口本店' WHERE id='ChIJC1Po7pKNGGARCJjA3_sCB3Y';
UPDATE restaurants SET name_zh='食彩云南 ムーさんの蒸锅馆 池袋 中华' WHERE id='ChIJUX7B-7WNGGARNzCuX64WjbY';
UPDATE restaurants SET name_zh='センス' WHERE id='ChIJAQlsfFWJGGARkVc-krREwKs';
UPDATE restaurants SET name_zh='SHEEPMAN シープマン 牧羊人' WHERE id='ChIJc66sSACPGGARAamebbJg-Iw';
UPDATE restaurants SET name_zh='一平饭店' WHERE id='ChIJIXrCrK-LGGARfx-SIkgR5Rs';
UPDATE restaurants SET name_zh='凡姐老火锅 上野本店' WHERE id='ChIJg7cZa8iPGGARt0B-E7To5Ok';
UPDATE restaurants SET name_zh='四川麻辣烫' WHERE id='ChIJKT7R3KSIGGARFjuFIkcR-Bc';
UPDATE restaurants SET name_zh='疆莱 新疆本场料理店' WHERE id='ChIJDTGQI8qNGGARtj3xiV1WbDk';
UPDATE restaurants SET name_zh='金陵 银座本店' WHERE id='ChIJ7W3hJPqLGGARIiBU3FV9Tek';
UPDATE restaurants SET name_zh='兰州' WHERE id='ChIJvcJwegCPGGARl8sXyTnF-JI';
UPDATE restaurants SET name_zh='中国乡土料理 优香刀削面 小台店' WHERE id='ChIJQXMsOA6NGGARVTiu9pl8qvc';
UPDATE restaurants SET name_zh='银座嘉禅' WHERE id='ChIJA2UBT--LGGARnpEtqCjIx6s';
UPDATE restaurants SET name_zh='名登利寿司 新小岩店' WHERE id='ChIJiQAoawOGGGAR4BUDcZupfj4';
UPDATE restaurants SET name_zh='モンゴルダイニングミシェール' WHERE id='ChIJLweRkEmHGGARYU-gTwp3C8w';
UPDATE restaurants SET name_zh='白鹿原ビャンビャン麵 新小岩店' WHERE id='ChIJOUiEVgCHGGARIP19UtpGxck';
UPDATE restaurants SET name_zh='一番麻辣烫·湖南香辣米粉' WHERE id='ChIJLyuDBeuNGGARoJT7qwvdjag';
UPDATE restaurants SET name_zh='韩国料理 金达莱' WHERE id='ChIJOzKPByaNGGARX80GMzSEs7Y';
UPDATE restaurants SET name_zh='中国料理 福来轩' WHERE id='ChIJQcW9c72OGGARv9wtnwjP9J8';
UPDATE restaurants SET name_zh='金陵一绝 王氏汤包' WHERE id='ChIJtdmo5xTtGGARU-2dT_eIrPM';
UPDATE restaurants SET name_zh='ようこそ酒場 龟户店' WHERE id='ChIJJ247clWJGGARyMOKKI6NqA8';
UPDATE restaurants SET name_zh='小河帮川菜池袋店' WHERE id='ChIJW9BAJWmNGGARKXvNnkFPc1o';
UPDATE restaurants SET name_zh='チャイニーズダイニング菜香' WHERE id='ChIJARrwiS-HGGARjGcvmQkO3qQ';
UPDATE restaurants SET name_zh='食光里 麻辣汤' WHERE id='ChIJUx0LdwCPGGARFT0DEFHVB7Q';
UPDATE restaurants SET name_zh='富锦树台菜香槟 Fujin Tree Taiwanese Cuisine & Champagne 原宿Quest店' WHERE id='ChIJqTtRAR2NGGAR4v77tko3uG4';
UPDATE restaurants SET name_zh='湖南香辣米粉（1F）' WHERE id='ChIJofLLskeNGGAR7z9PADmSr58';
UPDATE restaurants SET name_zh='哪吒麻辣汤 ナーザマーラータン' WHERE id='ChIJHxVEsY3zGGARg5CVbyVmCQQ';
UPDATE restaurants SET name_zh='香河' WHERE id='ChIJURZEcwOGGGARfXH2WeqjK0k';
UPDATE restaurants SET name_zh='桃猫麻辣汤（ももねこマーラータン）' WHERE id='ChIJeZLyWACPGGARSjKl_dJU6OA';
UPDATE restaurants SET name_zh='湘遇 池袋店' WHERE id='ChIJnQUHBACNGGARk6xCPODuEqg';
UPDATE restaurants SET name_zh='五粮液ダイニングTOKYO' WHERE id='ChIJ4eU-tKyLGGARDxawx6NBzg8';
UPDATE restaurants SET name_zh='ハラール中华 食遇·楼兰 ショクグウ オーラン' WHERE id='ChIJrTS8XwCNGGAReLcQT-ljw0I';
UPDATE restaurants SET name_zh='重庆饭店 麻布宾馆' WHERE id='ChIJwaL8zHCLGGARV1gErM4gBqY';
UPDATE restaurants SET name_zh='YAUMAY' WHERE id='ChIJLYR_1ciLGGARyF9B0VihIR8';
UPDATE restaurants SET name_zh='皓月麻辣汤 葛西（コウゲツ マーラータン）' WHERE id='ChIJhf7L1RuHGGARalvKiJWV1Rc';
UPDATE restaurants SET name_zh='杨国福マーラータン 新小岩店' WHERE id='ChIJ3YeaIf6HGGAR0ZzHb_CSnrY';
UPDATE restaurants SET name_zh='珍满茶楼' WHERE id='ChIJZQDzyP6FGGARSDOMRK19las';
UPDATE restaurants SET name_zh='福建家庭料理 旬之香' WHERE id='ChIJzQWHqMnyGGARaqbPvH90yag';
UPDATE restaurants SET name_zh='福清菜馆 福来园' WHERE id='ChIJ3dHTBl6NGGARDFSJVaSVm5M';
UPDATE restaurants SET name_zh='香辣里 シャンラーリー' WHERE id='ChIJh5poWLT1GGAR-r6WFp01pZw';
UPDATE restaurants SET name_zh='湘遇 高田马场店' WHERE id='ChIJVY5RoviNGGARVqL4T2Ydzy8';
UPDATE restaurants SET name_zh='虎景轩(フージン)' WHERE id='ChIJVa-abQCLGGARE_ojpz-MmZg';
UPDATE restaurants SET name_zh='四川鱼火锅、烤鱼、しゃぶしゃぶ专卖店（好上头）' WHERE id='ChIJzRSamJiNGGARw1-bgXMyIc4';
UPDATE restaurants SET name_zh='京华阁' WHERE id='ChIJCUPxU26NGGARiXeRseTSZQ0';
UPDATE restaurants SET name_zh='羊不同 上野店' WHERE id='ChIJ3YOFcNuNGGARRn9_Ktksj7k';
UPDATE restaurants SET name_zh='中国料理 喜羊门 上野店' WHERE id='ChIJy01YBj2PGGARSgGvBxuANRY';
UPDATE restaurants SET name_zh='中国江西料理 几道菜 上野店' WHERE id='ChIJpepTAFGNGGARA5XiVZs43Ig';
UPDATE restaurants SET name_zh='杨国福麻辣汤 银座店' WHERE id='ChIJiw4sdf6LGGARVG8vy_XiIM4';
UPDATE restaurants SET name_zh='四川麻辣汤 池袋本店' WHERE id='ChIJ3S6EZF6NGGARMjD5Mxv58KE';
UPDATE restaurants SET name_zh='完全個室×火锅中华 孙二娘潮汕牛肉火锅 上野御徒町本店' WHERE id='ChIJrSpS4eqNGGAR4AUhSWmjAC0';
UPDATE restaurants SET name_zh='五十番' WHERE id='ChIJNwNyxQSGGGARnndJrVc6qIk';
UPDATE restaurants SET name_zh='湘里人家' WHERE id='ChIJTy2nuk-NGGARGkEfw9qn3eU';
UPDATE restaurants SET name_zh='贵州火锅' WHERE id='ChIJuw-gL7uHGGARefhvQxJ2lBw';
UPDATE restaurants SET name_zh='粤熹粥档' WHERE id='ChIJZbQ1gieNGGAR_bB7g2oxUTU';
UPDATE restaurants SET name_zh='黔莊 贵州牛羊粉 Noodle villa 上野店' WHERE id='ChIJ99rLUBmNGGARaxy2mn7lCcE';
UPDATE restaurants SET name_zh='兰州牛肉面 一盛 龟户店' WHERE id='ChIJYfiyw7mJGGARI1nIkk4KsIs';
UPDATE restaurants SET name_zh='中华料理 秀永' WHERE id='ChIJJzm7RzyNGGARHBMDrsygR9E';
UPDATE restaurants SET name_zh='延吉香' WHERE id='ChIJc-Z_b6iNGGARiNWeH-AkPi8';
UPDATE restaurants SET name_zh='中国料理 扬州名菜 秦淮春 三笠会馆本店' WHERE id='ChIJ1SYZ5OWLGGARu0bR3mPjqEw';
UPDATE restaurants SET name_zh='ウイグルレストラン シルクロード・タリム(新疆料理)' WHERE id='ChIJ9WBWai3zGGAR4PZkxBzZs10';
UPDATE restaurants SET name_zh='广东料理 龙门天' WHERE id='ChIJO4Ou6haLGGARDFU3j1ko508';
UPDATE restaurants SET name_zh='火焰山兰州拉面 池袋店' WHERE id='ChIJiW_jF16NGGARG7ClK7-_n7U';
UPDATE restaurants SET name_zh='蒸笼味坊' WHERE id='ChIJbfSm4J_zGGARi_DnbKq4Aek';
UPDATE restaurants SET name_zh='天山见 长安大牌档・西北本场料理店・刀削面(Halal Food)' WHERE id='ChIJ4a5h212PGGAR-sLTTGle-w4';
UPDATE restaurants SET name_zh='中华料理 聚福楼 池袋' WHERE id='ChIJS-P41V2NGGAR8icE00p4mmg';
UPDATE restaurants SET name_zh='香港料理 盛记 SEIKI GINZA' WHERE id='ChIJNUw--86LGGARKmS-2ru1nsA';
UPDATE restaurants SET name_zh='民记煲仔饭' WHERE id='ChIJu8fl-oeNGGAROyXlX-d9flI';
UPDATE restaurants SET name_zh='乐乐屋 池袋本店' WHERE id='ChIJ4XS7_F2NGGAR1ceJXZc5UTs';
UPDATE restaurants SET name_zh='菌菇锅＆菌菇料理 何鲜菇' WHERE id='ChIJfx8CLtGPGGARrHDKznucOCA';
UPDATE restaurants SET name_zh='广东料理 福萬年' WHERE id='ChIJN5tphaCOGGARHm86HPLQfGI';
UPDATE restaurants SET name_zh='餐厅 香港' WHERE id='ChIJ84PeRabyGGARmAz8GuMZCHE';
UPDATE restaurants SET name_zh='中国料理喜羊门' WHERE id='ChIJCa8YRSCMGGARrONVBd5V5nA';
UPDATE restaurants SET name_zh='香港1997 銀座トレシャス店' WHERE id='ChIJB6OrDeSLGGARddUjWet7WpE';
UPDATE restaurants SET name_zh='中国饭店 紫玉兰' WHERE id='ChIJR4m5ypiLGGARdLG8EpsHHnY';
UPDATE restaurants SET name_zh='牛家兄弟兰州牛肉面新宿店（Halal）' WHERE id='ChIJFdplFJqNGGAR_j5Ya03TFV4';
UPDATE restaurants SET name_zh='杨国福（ヤンゴーフー）池袋东口店' WHERE id='ChIJVfO4KoONGGAR4zxZGO8ae3c';
UPDATE restaurants SET name_zh='香港面新记 三宿本店' WHERE id='ChIJeZ4m8ab0GGARhwtCR-yAMIg';
UPDATE restaurants SET name_zh='花临 兰州牛肉面' WHERE id='ChIJe1GlRU6NGGARIvyAuXYJamg';
UPDATE restaurants SET name_zh='CANTON8/喜粤8号' WHERE id='ChIJ1wypgf6LGGARR_rTdi8vDb8';
UPDATE restaurants SET name_zh='马子禄牛肉面 神保町店' WHERE id='ChIJg96PHRGMGGARBK5mBzz9N04';
UPDATE restaurants SET name_zh='中国料亭 翠凤 上野本店' WHERE id='ChIJ8c4f2J6OGGAREWWg6WjuJt8';
UPDATE restaurants SET name_zh='中华酒场 老妈 麻辣汤' WHERE id='ChIJWzqSWNOHGGARKmnNmOTwDIc';
UPDATE restaurants SET name_zh='香港饮茶点心厨房' WHERE id='ChIJDcIQ62ONGGARFO7-K9sHg38';
UPDATE restaurants SET name_zh='晴々饭店' WHERE id='ChIJ6YpA3JuOGGAR97RW9IJDzpM';
UPDATE restaurants SET name_zh='永利 池袋本店' WHERE id='ChIJoYrlmGCNGGARPMFg7cdBVIY';
UPDATE restaurants SET name_zh='南京亭 瑞穂店' WHERE id='ChIJoTZiRZwgGWARw_S-WIiQInU';
UPDATE restaurants SET name_zh='イケチカ ダイニング' WHERE id='ChIJ8xr7mF2NGGARzUkhuSBqsg8';
UPDATE restaurants SET name_zh='千里香 上野本店' WHERE id='ChIJHeJ-C5-OGGARgZFNoQdqiKc';
UPDATE restaurants SET name_zh='友誼食府' WHERE id='ChIJvbQjwzKNGGARWxJuQ14BYxA';
UPDATE restaurants SET name_zh='香港面新记 四谷三丁目店' WHERE id='ChIJG8cnbO2MGGARjVF6x0QM83s';
UPDATE restaurants SET name_zh='中国茶芸苑 馥' WHERE id='ChIJMf93ekaMGGARjBuunHcLQK8';
